#spring.application.name=indentityservice

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/Identity_service
      username: root
      password: root

  jpa:
    hibernate:
      ddl-auto: update # Tu dong tao bang neu nhu chua co
    show-sql: true #debug query string SQL

server:
  port: 8080
  servlet:
    context-path: /identity