#spring.application.name=indentityservice

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/Identity_service
      username: root
      password: root

  jpa:
    hibernate:
      ddl-auto: update # Tu dong tao bang neu nhu chua co
    show-sql: true #debug query string SQL
jwt:
  signerKey: "mH4CblTDofPnUtYvO/xcmbyKFMN/S+B9GD7RCt9i7YdAtqm5DdxefbjMwPNb7E/USYC/MGw1TVeuT9kZ/H6DRYeMp/uBJqIZ5KhnBvoNZpqdfWO/HZeghTPpykryMkTT0dlUgOwfJSFNZI/P0ABxM2rum+u3/hCuYjIveZLy6AG5cafUn1AVX5ZJkJNmOxqe/QR8b9LTrXuzdIOa5jY/gYpLH8dQwwhjw8cLCnICP4g4PSHJIZAcDBthVD0J4IaKK59/0AbZU7LYvy2G8S2mlIcMiVY2fPrFG12fdIh+1ypS1+iFsZEv/rUQnTqPiCRSQYkQPnSZJ7T9rDeIOK81Rw=="
server:
  port: 8080
  servlet:
    context-path: /identity